default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: postgres
  password:

development:
  <<: *default
  host: <%= Rails.application.credentials.dig(:database, ENV.fetch('DB_CONFIG') { 'default' }.to_sym, :host) || 'db' %>
  port: <%= Rails.application.credentials.dig(:database, ENV.fetch('DB_CONFIG') { 'default' }.to_sym, :port) || 5432 %>
  username: <%= Rails.application.credentials.dig(:database, ENV.fetch('DB_CONFIG') { 'default' }.to_sym, :username) || 'postgres' %>
  password: <%= Rails.application.credentials.dig(:database, ENV.fetch('DB_CONFIG') { 'default' }.to_sym, :password) || '' %>
  database: <%= Rails.application.credentials.dig(:database, ENV.fetch('DB_CONFIG') { 'default' }.to_sym, :db_name) || 'app_development' %>

test:
  <<: *default
  database: app_test

production:
  <<: *default
  host: <%= Rails.application.credentials.dig(:database, :host) %>
  port: <%= Rails.application.credentials.dig(:database, :port) %>
  username: <%= Rails.application.credentials.dig(:database, :username) %>
  password: <%= Rails.application.credentials.dig(:database, :password) %>
  database: <%= Rails.application.credentials.dig(:database, :db_name) %>
